### Variables 
@apiurl = http://localhost:3000/api

### watchs
GET {{apiurl}}/watch?p=0&category=Relógios Femininos&brand= HTTP/1.1


### categories
GET {{apiurl}}/category HTTP/1.1


### brands
GET {{apiurl}}/brand HTTP/1.1
