### Variables 
@apiurl = http://localhost:3000/api

### watchs
GET {{apiurl}}/watch?p=1&category=Relógios Masculinos&brand=&priceMin=50&priceMax=522.98 HTTP/1.1


### categories
GET {{apiurl}}/category HTTP/1.1


### brands
GET {{apiurl}}/brand HTTP/1.1
